jwt:
  secret: tOpStXDMXpCj19sCAMy73pBNiKHqUiK67ZjlgvIlwvtaz5BAcMJbyjU

spring:
  data:
    mongodb:
      host: 127.0.0.1
#      host: 125.191.254.22
      port: 27017
      database: chat
      authentication-database: test
server:
  port: 8080
