jwt:
  secret: YmxpbmtwYXNzd29yZA==

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat
    mysql:
      url: jdbc:mysql://localhost:3306/room
      username: root
      password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
